[sim]
t0 = { val = 0, dtype = "f64" }
dt = { val = 0.01, dtype = "f64" }
max_t =  { val = 90, dtype = "f64" }

[sim.rocket.crater]
mass = { val = 2, dtype = "f64" }
inertia = { val = [0.005, 0.26, 0.26], dtype = "f64" }

[sim.rocket.crater.init]
azimuth = { val = 10, dtype = "f64" }
elevation = { val = 85, dtype = "f64" }
 
[sim.rocket.crater.engine]
engine_type = { val = "simple", dtype = "string" }

simple.total_impulse = { val = 320, dtype = "f64" }
simple.thrust_duration = { val = 6, dtype = "f64" }
